package entidades;
// Generated Jun 4, 2015 2:33:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private int id;
     private Usuario usuario;
     private String descricao;
     private Set produtos = new HashSet(0);

    public Departamento() {
    }

	
    public Departamento(int id, Usuario usuario, String descricao) {
        this.id = id;
        this.usuario = usuario;
        this.descricao = descricao;
    }
    public Departamento(int id, Usuario usuario, String descricao, Set produtos) {
       this.id = id;
       this.usuario = usuario;
       this.descricao = descricao;
       this.produtos = produtos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set produtos) {
        this.produtos = produtos;
    }




}


