package entidades;
// Generated Jun 4, 2015 2:33:30 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Saida generated by hbm2java
 */
public class Saida  implements java.io.Serializable {


     private int id;
     private Cliente cliente;
     private Produto produto;
     private Usuario usuario;
     private Date data;
     private BigDecimal preco;
     private int quantidade;
     private int total;

    public Saida() {
    }

    public Saida(int id, Cliente cliente, Produto produto, Usuario usuario, Date data, BigDecimal preco, int quantidade, int total) {
       this.id = id;
       this.cliente = cliente;
       this.produto = produto;
       this.usuario = usuario;
       this.data = data;
       this.preco = preco;
       this.quantidade = quantidade;
       this.total = total;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public BigDecimal getPreco() {
        return this.preco;
    }
    
    public void setPreco(BigDecimal preco) {
        this.preco = preco;
    }
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }
    public int getTotal() {
        return this.total;
    }
    
    public void setTotal(int total) {
        this.total = total;
    }




}


