package entidades;
// Generated Jun 4, 2015 2:33:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int id;
     private String nome;
     private String login;
     private String senha;
     private Set produtos = new HashSet(0);
     private Set clientes = new HashSet(0);
     private Set saidas = new HashSet(0);
     private Set departamentos = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int id, String nome, String login, String senha) {
        this.id = id;
        this.nome = nome;
        this.login = login;
        this.senha = senha;
    }
    public Usuario(int id, String nome, String login, String senha, Set produtos, Set clientes, Set saidas, Set departamentos) {
       this.id = id;
       this.nome = nome;
       this.login = login;
       this.senha = senha;
       this.produtos = produtos;
       this.clientes = clientes;
       this.saidas = saidas;
       this.departamentos = departamentos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public Set getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set produtos) {
        this.produtos = produtos;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }
    public Set getSaidas() {
        return this.saidas;
    }
    
    public void setSaidas(Set saidas) {
        this.saidas = saidas;
    }
    public Set getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Set departamentos) {
        this.departamentos = departamentos;
    }




}


