package br.com.fatec.entidades;
// Generated Jun 8, 2015 11:54:33 PM by Hibernate Tools 4.3.1



/**
 * Fornecedor generated by hbm2java
 */
public class Fornecedor  implements java.io.Serializable {


     private int id;
     private Usuario usuario;
     private String cnpj;
     private String nome;
     private String endereco;

    public Fornecedor() {
    }

    public Fornecedor(int id, Usuario usuario, String cnpj, String nome, String endereco) {
       this.id = id;
       this.usuario = usuario;
       this.cnpj = cnpj;
       this.nome = nome;
       this.endereco = endereco;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }




}


