package br.com.fatec.entidades;
// Generated Jun 8, 2015 11:54:33 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


     private int id;
     private Departamento departamento;
     private Usuario usuario;
     private String descricao;
     private BigDecimal precoCusto;
     private BigDecimal preco;
     private int quantidade;
     private Date dataCadastro;
     private int margemEstoque;
     private Set saidas = new HashSet(0);

    public Produto() {
    }

	
    public Produto(int id, Departamento departamento, Usuario usuario, BigDecimal precoCusto, BigDecimal preco, int quantidade, Date dataCadastro, int margemEstoque) {
        this.id = id;
        this.departamento = departamento;
        this.usuario = usuario;
        this.precoCusto = precoCusto;
        this.preco = preco;
        this.quantidade = quantidade;
        this.dataCadastro = dataCadastro;
        this.margemEstoque = margemEstoque;
    }
    public Produto(int id, Departamento departamento, Usuario usuario, String descricao, BigDecimal precoCusto, BigDecimal preco, int quantidade, Date dataCadastro, int margemEstoque, Set saidas) {
       this.id = id;
       this.departamento = departamento;
       this.usuario = usuario;
       this.descricao = descricao;
       this.precoCusto = precoCusto;
       this.preco = preco;
       this.quantidade = quantidade;
       this.dataCadastro = dataCadastro;
       this.margemEstoque = margemEstoque;
       this.saidas = saidas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public BigDecimal getPrecoCusto() {
        return this.precoCusto;
    }
    
    public void setPrecoCusto(BigDecimal precoCusto) {
        this.precoCusto = precoCusto;
    }
    public BigDecimal getPreco() {
        return this.preco;
    }
    
    public void setPreco(BigDecimal preco) {
        this.preco = preco;
    }
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public int getMargemEstoque() {
        return this.margemEstoque;
    }
    
    public void setMargemEstoque(int margemEstoque) {
        this.margemEstoque = margemEstoque;
    }
    public Set getSaidas() {
        return this.saidas;
    }
    
    public void setSaidas(Set saidas) {
        this.saidas = saidas;
    }




}


